# Practical Exam: House sales

RealAgents is a real estate company that focuses on selling houses.

RealAgents sells a variety of types of house in one metropolitan area.

Some houses sell slowly and sometimes require lowering the price in order to find a buyer.

In order to stay competitive, RealAgents would like to optimize the listing prices of the houses it is trying to sell.

They want to do this by predicting the sale price of a house given its characteristics.

If they can predict the sale price in advance, they can decrease the time to sale.


## Data

The dataset contains records of previous houses sold in the area.

| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
| house_id    | Nominal. </br> Unique identifier for houses. </br>Missing values not possible. |
| city        | Nominal. </br>The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton'. </br>Replace missing values with "Unknown". |
| sale_price  | Discrete. </br>The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero.</br>Remove missing entries. |
| sale_date   | Discrete. </br>The date of the last sale of the house. </br>Replace missing values with 2023-01-01. |
| months_listed  | Continuous. </br>The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. </br>Replace missing values with mean number of months listed, to one decimal place. |
| bedrooms    | Discrete. </br>The number of bedrooms in the house. Any positive values greater than or equal to zero. </br>Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| house_type   | Ordinal. </br>One of "Terraced" (two shared walls), "Semi-detached" (one shared wall), or "Detached" (no shared walls). </br>Replace missing values with the most common house type. |
| area      | Continuous. </br>The area of the house in square meters, rounded to one decimal place. </br>Replace missing values with the mean, to one decimal place. |

# Task 1

The team at RealAgents knows that the city that a property is located in makes a difference to the sale price. 

Unfortuntately they believe that this isn't always recorded in the data. 

Calculate the number of missing values of the `city`. 

 - You should use the data in the file "house_sales.csv". 

 - Your output should be an object `missing_city`, that contains the number of missing values in this column.

In [1]:
# Use this cell to write your code for Task 1
import pandas as pd
pd.set_option('display.max_columns', None)
clean_data = pd.read_csv('house_sales.csv')
#exploring the data
print(clean_data.head())
print(clean_data.info())
#looking for null values in the columns
print(clean_data.isna().sum())
#examining the city column
print(clean_data['city'].value_counts())
#the missing values in the city have --. we will count those values
missing_city = len(clean_data[clean_data['city'] == '--'])
print(missing_city)

   house_id        city  sale_price   sale_date  months_listed  bedrooms  \
0   1217792  Silvertown       55943  2021-09-12            5.4         2
1   1900913  Silvertown      384677  2021-01-17            6.3         5
2   1174927   Riverford      281707  2021-11-10            6.9         6
3   1773666  Silvertown      373251  2020-04-13            6.1         6
4   1258487  Silvertown      328885  2020-09-24            8.7         5

      house_type         area
0  Semi-detached  107.8 sq.m.
1       Detached  498.8 sq.m.
2       Detached  542.5 sq.m.
3           Det.  528.4 sq.m.
4       Detached  477.1 sq.m.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   house_id       1500 non-null   int64
 1   city           1500 non-null   object
 2   sale_price     1500 non-null   int64
 3   sale_date      1500 non-null   object
 4   months_listed  1469 non-null   float64
 5   bedrooms       1500 non-null   int64
 6   house_type     1500 non-null   object
 7   area           1500 non-null   object
dtypes: float64(1), int64(3), object(4)
memory usage: 93.9+ KB
None
house_id          0
city              0
sale_price        0
sale_date         0
months_listed    31
bedrooms          0
house_type        0
area              0
dtype: int64
city
Silvertown    517
Teasdale      366
Poppleton     362
Riverford     182
--             73
Name: count, dtype: int64
73

# Task 2 

Before you fit any models, you will need to make sure the data is clean. 

The table below shows what the data should look like. 

Create a cleaned version of the dataframe. 

 - You should start with the data in the file "house_sales.csv". 

 - Your output should be a dataframe named `clean_data`. 

 - All column names and values should match the table below.


| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
| house_id    | Nominal. </br> Unique identifier for houses. </br>Missing values not possible. |
| city        | Nominal. </br>The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton' </br>Replace missing values with "Unknown". |
| sale_price  | Discrete. </br>The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero.</br>Remove missing entries. |
| sale_date   | Discrete. </br>The date of the last sale of the house. </br>Replace missing values with 2023-01-01. |
| months_listed  | Continuous. </br>The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. </br>Replace missing values with mean number of months listed, to one decimal place. |
| bedrooms    | Discrete. </br>The number of bedrooms in the house. Any positive values greater than or equal to zero. </br>Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| house_type   | Ordinal. </br>One of "Terraced", "Semi-detached", or "Detached". </br>Replace missing values with the most common house type. |
| area      | Continuous. </br>The area of the house in square meters, rounded to one decimal place. </br>Replace missing values with the mean, to one decimal place. |

In [10]:
#CITY COLUMN CLEANING
#checking the datatype of the city column
print(f"The data type for the city column is : {clean_data['city'].dtype}")
#replacing incorrect city values with Unknown
clean_data['city'] = clean_data['city'].str.replace('--','Unknown')
#examining changes
print(clean_data['city'].value_counts())

#SALE_PRICE COLUMN CLEANING
#checking the datatype of the sale_price column
print(f"The data type for sale_price column is : {clean_data['sale_price'].dtype}")
#checking for values less than or equal to zero in the sale_price column
incorrect_sale_price = clean_data[clean_data['sale_price'] <= 0]
print(f"The number of incorrect sale_price values are: {len(incorrect_sale_price)}")

#SALE DATE COLUMN CLEANING
#checking the datatype of the sale_date column
print(f"The data type for the sale_date column is : {clean_data['sale_date'].dtype}")
#checking for missing values in the  sale_date column
missing_sale_date = clean_data['sale_date'].isna().sum()
print(f"The number of missing sale_date values is: {missing_sale_date}")

#MONTHS_LISTED COLUMN CLEANING
#checking the datatype of the months_listed column
print(f"The data type for months_listed column is : {clean_data['months_listed'].dtype}")
#checking for missing values in the  months_listed column
missing_months_listed = clean_data['months_listed'].isna().sum()
print(f"The number of missing months_listed values is: {missing_months_listed}")
#replacing missing months listed with the mean number of months listed, to one decimal place
clean_data['months_listed'] = clean_data['months_listed'].fillna(round(clean_data['months_listed'].mean(), 1))
#examining changes
missing_months_listed_2 = clean_data['months_listed'].isna().sum()
print(f"The number of missing months_listed values after changes is: {missing_months_listed_2}")

#BEDROOMS COLUMN CLEANING
print(f"The data type for the bedrooms column is : {clean_data['bedrooms'].dtype}")
#checking for missing values in the  months_listed column
missing_bedrooms = clean_data['bedrooms'].isna().sum()
print(f"The number of missing bedrooms values is: {missing_bedrooms}")

#HOUSE TYPE COLUMN CLEANING
print(f"The data type for the house_type column is : {clean_data['house_type'].dtype}")
#checking for missing values in the house_type column
missing_house_type = clean_data['house_type'].isna().sum()
print(f"The number of missing house value is: {missing_house_type}")
#examining the values of house_type
print(clean_data['house_type'].value_counts())
#replacing Det., Semi. & Terr. with Detached, Semi-detached and Terrace
clean_data['house_type'] = clean_data['house_type'] = clean_data['house_type'].replace({
    'Det.': 'Detached',
    'Semi': 'Semi-detached', 
    'Terr.': 'Terraced'
})
#examining changes
print(clean_data['house_type'].value_counts())

#AREA COLUMN CLEANING
print(f"The data type for the area column is : {clean_data['area'].dtype}")
print(clean_data['area'].value_counts())
#removing 'sq.m.' from the area column
clean_data['area'] = clean_data['area'].str.replace('sq.m.', '',regex=False)
#removing any extra whitespace
clean_data['area'] = clean_data['area'].str.strip()
#changing the datatype of area column to float
clean_data['area'] = clean_data['area'].astype('float') 
#checking for missing values in the area column
missing_area = clean_data['area'].isna().sum()
print(f"The number of missing area values is: {missing_area}")
#examing changes
print(clean_data['area'].dtype)

The data type for the city column is : object
city
Silvertown    517
Teasdale      366
Poppleton     362
Riverford     182
Unknown        73
Name: count, dtype: int64
The data type for sale_price column is : int64
The number of incorrect sale_price values are: 0
The data type for the sale_date column is : object
The number of missing sale_date values is: 0
The data type for months_listed column is : float64
The number of missing months_listed values is: 0
The number of missing months_listed values after changes is: 0
The data type for the bedrooms column is : int64
The number of missing bedrooms values is: 0
The data type for the house_type column is : object
The number of missing house value is: 0
house_type
Detached         1124
Semi-detached     245
Terraced          131
Name: count, dtype: int64
house_type
Detached         1124
Semi-detached     245
Terraced          131
Name: count, dtype: int64
The data type for the area column is : float64
area
124.3    4
307.3    3
336.5    3
424.8    3
371.4    3
        ..
535.5    1
485.1    1
294.9    1
109.6    1
268.7    1
Name: count, Length: 1282, dtype: int64

AttributeError: Can only use .str accessor with string values!

# Task 3 

The team at RealAgents have told you that they have always believed that the number of bedrooms is the biggest driver of house price. 

Producing a table showing the difference in the average sale price by number of bedrooms along with the variance to investigate this question for the team.

 - You should start with the data in the file 'house_sales.csv'.

 - Your output should be a data frame named `price_by_rooms`. 

 - It should include the three columns `bedrooms`, `avg_price`, `var_price`. 

 - Your answers should be rounded to 1 decimal place.

In [12]:
# Use this cell to write your code for Task 3
#creating by_rooms
by_rooms = clean_data[['bedrooms','sale_price']]
#grouping by_rooms by sale_price and calculating the average to create the avg_price and var_price columns
price_by_rooms = by_rooms.groupby('bedrooms')['sale_price'].agg(['mean','var']).reset_index().rename({'mean':'avg_price','var':'var_price'})
#rounding the avg_price to 1 decimal place
price_by_rooms['avg_price'] = round(price_by_rooms['avg_price'],1)
#rounding the avg_price to 1 decimal place
price_by_rooms['var_price'] = round(price_by_rooms['var_price'],1)
#examining the changes
print(price_by_rooms)

KeyError: 'avg_price'

# Task 4

Fit a baseline model to predict the sale price of a house.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “validation.csv” to predict new values based on your model. You must return a dataframe named `base_result`, that includes `house_id` and `price`. The price column must be your predicted values.

In [4]:
# Use this cell to write your code for Task 4

# Task 5

Fit a comparison model to predict the sale price of a house.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “validation.csv” to predict new values based on your model. You must return a dataframe named `compare_result`, that includes `house_id` and `price`. The price column must be your predicted values.

In [5]:
# Use this cell to write your code for Task 5